### PR TITLE
Add support for new CAS file formats

### LINKED ISSUE #78: parser not working, resulting in excalamation mark / error rather than checked
I generated a consolidated report from CAS - CAMS + KFintech at https://www.camsonline.com/Investors/Statements/Consolidated-Account-Statement

Executing the casparser cli utility does not return successfully.

Is this expected ?

Please note the Error and the Excalamation marks in the image below.

casparser_snippet_error

Command executed,

`$ casparser <filename>.pdf -p '<$password$>'`

File Type details,

> File Type : FileType.CAMS                                                                                     
                                                                 CAS Type : CASFileType.DETAILED  

also, is up-to-date,

```
(.venv_py310) iceman@pop-os ~/D/M/Statements> casparser-isin --update
2023-08-31 00:26:23,325 - INFO - Fetching remote isin db metadata
2023-08-31 00:26:24,283 - INFO - Local db version  : 2023.8.18
2023-08-31 00:26:24,283 - INFO - Remote db version : 2023.8.18
2023-08-31 00:26:24,283 - INFO - casparser-isin database is already upto date
```

### PR DESCRIPTION
**Pull request by codereverser**
- add support for both old and new CAS file formats
- better regexp queries
- update pydantic to v2

fixes #78

### CODE REVIEW

**Comment by isaac-philip** [comment]
Thanks for the quick turn-around time.

So what I am observing is a new issue !!

For me, its unable to gather the **11** schemes that were previously showing in `Total`.
Now it shows below with green ticks for random `6`,
I assume these 6 are computed only while others are skipped / ignored ?

Output summary i get for the same report earlier raised,
```
Summary
Total   :    6 schemes
Matched :    6 schemes
Error   :    0 schemes
```

and just does not show anything about the remaining 4 or 5(considering 0 balance) schemes in the portfolio.

**Comment by isaac-philip** [comment]
::my environment::

- python version - Python 3.10.6

for some reason does not install sqllite3 on python3.8.18 ?
I installed using,

```
$ pip install .
```

**Comment by codereverser** [comment]
By default it doesn't print 0 balance rows, to avoid clutter. You can print all schemes by passing `-a` / `--include-all` option

```
  -a, --include-all           Include schemes with zero valuation in the
                              summary output
```

> for some reason does not install sqllite3 on python3.8.18 

not sure about this. sqlite3 is supposed to be part of standard python library. may be some issue with the python setup?

**Comment by isaac-philip** [comment]
took pull, installed latest `Successfully installed casparser-0.7.1`,

Only 1 scheme was 0 valued, like I said the issue that I raised earlier showed 11 schemes but here it shows only 6 for some reason inspite of using the `-a` param too.

**Comment by codereverser** [comment]
Oh. I missed that. Let me check again.

Can you send a partial screenshot of the missing schemes ?(you may hide any sensitive info).

**Comment by codereverser** [comment]
@isaac-philip I've pushed one more commit that may solve the issue. Can you please give it a try? 

The code works fine on all CAS files I use for testing; so not sure how to fix this frankly, if it still doesn't work 😐

**Comment by isaac-philip** [comment]
Unfortunately it's the same :(

**Comment by isaac-philip** [comment]
I'll have a look to debug this, I also can't seem to find a way to share the file without revealing sensitive info.

I tried to black out but after testing  the file with execution and still the name and other details were displayed on screen.

**Comment by isaac-philip** [comment]
latest code I tested wit d same pdf, works perfect 👍🏼 

Details checked,

- Summary Total equals Matched ✅ 
- Summary - No Error ✅ 
- Portfolio Valuation data is matching the report/pdf ✅ 

Thanks ! 😃

**Pull request merged**
